# defines the PEER2PEER protocol and PEER2SERVER protocol.

#Server 2 Peer
OPT_RES_LIST = 10
OPT_RES_OBJ = 11
OPT_RES_UPDATE_STAT = 12         #the last 2 isn't really needed?
OPT_RES_UPDATE_STOP = 13

# PEER 2 SERVER              
OPT_GET_LIST = 10
OPT_GET_TORRENT = 11
OPT_START_SEED = 12
OPT_STOP_SEED = 13
OPT_UPLOAD_FILE = 14

RET_SUCCESS = 0
RET_FAIL = -1

# PEER 2 PEER
OPT_STATUS_INTERESTED = 1
OPT_STATUS_UNINTERESTED = 2
OPT_STATUS_CHOKED = 3
OPT_STATUS_UNCHOKED = 4
OPT_GET_PEERS = 5
OPT_GET_PIECE = 6

# We should consider adding the payload names here and use it globally across our programs.
# For example:

OPC = 'OPC'
RET = 'RET'
IP = 'IP_ADDRESS'
PORT = 'PORT'
PID = 'PEER_ID'
TID = 'TORRENT_ID'
FILE_NAME = 'FILE_NAME'
TOTAL_PIECES = 'NUM_OF_PIECES'
TORRENT_LIST = 'TORRENT_LIST'
TORRENT = 'TORRENT_OBJ'
PIECE_IDX = 'PIECE_IDX'
PIECE_DATA = 'PIECE_DATA'
PEER_LIST = 'PEER_LIST'


PIECE_SIZE = 4096